In [1]:
import torch
import torchvision
from torchvision.datasets import MNIST
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

D:\2_Miniconda\lib\site-packages\torchvision\io\image.py:11: UserWarning: Failed to load image Python extension: Could not find module 'D:\2_Miniconda\Lib\site-packages\torchvision\image.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
  warn(f"Failed to load image Python extension: {e}")


In [2]:
dataset=MNIST(root='data/',download=True)

In [3]:
len(dataset)

60000

In [26]:
test_dataset=MNIST(root='data/',train=False)
len(test_dataset)

10000

In [27]:
dataset[0]

(tensor([[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 

In [28]:
image,label=dataset[0]


In [29]:
import torchvision.transforms as transforms

In [30]:
dataset=MNIST(root='data/',train=True,transform=transforms.ToTensor())

In [31]:
img_tensor, label =dataset[0]
print(img_tensor.shape,label)

torch.Size([1, 28, 28]) 5


In [32]:
print(img_tensor[:,10:15,10:15])
print(torch.max(img_tensor),torch.min(img_tensor))

tensor([[[0.0039, 0.6039, 0.9922, 0.3529, 0.0000],
         [0.0000, 0.5451, 0.9922, 0.7451, 0.0078],
         [0.0000, 0.0431, 0.7451, 0.9922, 0.2745],
         [0.0000, 0.0000, 0.1373, 0.9451, 0.8824],
         [0.0000, 0.0000, 0.0000, 0.3176, 0.9412]]])
tensor(1.) tensor(0.)


In [33]:
n=6000
val_pct=0.2
n_val=int(val_pct*n)
idxs=np.random.permutation(n)
idxs


array([ 997, 2085, 2755, ..., 3856, 5679, 3645])

In [34]:


def split_indices(n, val_pct):
    n_val=int(val_pct*n)
    idxs=np.random.permutation(n)
    return idxs[n_val:], idxs[:n_val]

In [35]:
train_indices, val_indices=split_indices(len(dataset),val_pct=0.2)

In [36]:
print(len(train_indices),len(val_indices))
print('Sample val indices: ',val_indices[:20])

48000 12000
Sample val indices:  [56916 18251 38650 23889 35545 42372 53673 30384 48666  7399 25653 34816
  3521 34775 53316 48806 43298 42647 23288  8974]


In [37]:
from torch.utils.data.sampler import SubsetRandomSampler
from torch.utils.data.dataloader import DataLoader

In [38]:
batch_size=100

train_sampler=SubsetRandomSampler(train_indices)
train_loader=DataLoader(dataset,batch_size,sampler=train_sampler)

val_sampler=SubsetRandomSampler(val_indices)
val_loader=DataLoader(dataset,batch_size,sampler=val_sampler)

In [39]:
import torch.nn as nn
input_size=28*28
num_classes=10

model=nn.Linear(input_size,num_classes)

In [40]:
print(model.weight.shape)
model.weight

torch.Size([10, 784])


Parameter containing:
tensor([[ 0.0072, -0.0197,  0.0316,  ..., -0.0050,  0.0357, -0.0127],
        [-0.0015,  0.0138,  0.0333,  ...,  0.0082, -0.0019, -0.0190],
        [-0.0290, -0.0018, -0.0059,  ...,  0.0175, -0.0003,  0.0057],
        ...,
        [ 0.0080,  0.0264,  0.0258,  ...,  0.0020,  0.0152, -0.0114],
        [ 0.0226, -0.0357, -0.0080,  ..., -0.0174, -0.0208,  0.0032],
        [ 0.0082, -0.0091,  0.0222,  ..., -0.0012, -0.0266, -0.0350]],
       requires_grad=True)

In [41]:
print(model.bias.shape)
model.bias

torch.Size([10])


Parameter containing:
tensor([ 0.0235,  0.0084,  0.0268,  0.0243,  0.0049, -0.0234,  0.0169, -0.0275,
        -0.0290, -0.0205], requires_grad=True)

In [42]:
for images, labels in train_loader:
    print(labels)
    print(images.shape)
    outputs=model(images)
    break

tensor([7, 0, 6, 7, 6, 1, 3, 6, 4, 5, 4, 6, 4, 4, 0, 9, 9, 9, 9, 3, 6, 6, 6, 5,
        1, 5, 4, 7, 5, 1, 2, 9, 0, 6, 2, 0, 4, 2, 2, 0, 2, 9, 6, 8, 9, 9, 2, 9,
        9, 6, 0, 9, 0, 5, 4, 8, 4, 2, 4, 4, 1, 7, 5, 7, 9, 5, 9, 3, 6, 2, 7, 6,
        4, 7, 2, 2, 3, 6, 7, 6, 8, 2, 6, 3, 9, 8, 9, 4, 2, 7, 7, 0, 6, 1, 9, 5,
        3, 0, 1, 0])
torch.Size([100, 1, 28, 28])


RuntimeError: mat1 and mat2 shapes cannot be multiplied (2800x28 and 784x10)

In [43]:
class MnistModel(nn.Module):

    def __init__(self):
        print(input_size)
        super().__init__()
        self.linear=nn.Linear(input_size,num_classes)

    def forward(self,xb):
        
        xb=xb.reshape(-1,784)
        out=self.linear(xb)
        return out
    
model=MnistModel()

784


In [44]:
print(model.linear.weight.shape, model.linear.bias.shape)
list(model.parameters())

torch.Size([10, 784]) torch.Size([10])


[Parameter containing:
 tensor([[-0.0006,  0.0029, -0.0067,  ..., -0.0182,  0.0094,  0.0066],
         [-0.0261,  0.0134, -0.0162,  ..., -0.0205, -0.0272,  0.0110],
         [ 0.0012,  0.0085,  0.0249,  ..., -0.0066, -0.0171,  0.0024],
         ...,
         [ 0.0295, -0.0108, -0.0100,  ..., -0.0277, -0.0114,  0.0076],
         [-0.0272,  0.0036,  0.0021,  ...,  0.0060, -0.0202,  0.0046],
         [ 0.0031,  0.0088,  0.0300,  ..., -0.0334, -0.0277,  0.0270]],
        requires_grad=True),
 Parameter containing:
 tensor([-0.0196,  0.0187, -0.0347, -0.0213,  0.0314, -0.0067,  0.0042, -0.0156,
          0.0256,  0.0227], requires_grad=True)]

In [45]:
for images, labels in train_loader:
    outputs=model(images)
    
    break
print('outputs.shape: ',outputs.shape)
print("Sample outputs:\n",outputs[:2].data)


outputs.shape:  torch.Size([100, 10])
Sample outputs:
 tensor([[-0.2559,  0.2447, -0.0024,  0.2525,  0.3066, -0.0949,  0.1173,  0.0169,
          0.0188,  0.0704],
        [-0.3550,  0.1096,  0.0980,  0.2074,  0.0858, -0.2493,  0.2912,  0.0657,
          0.1202,  0.1682]])


In [46]:
import torch.nn.functional as F

In [47]:
probs=F.softmax(outputs, dim=1)
print("Sample probabilities:\n",probs[:2].data)
print("Sum: ",torch.sum(probs[0]).item())

Sample probabilities:
 tensor([[0.0714, 0.1179, 0.0921, 0.1188, 0.1254, 0.0839, 0.1038, 0.0938, 0.0940,
         0.0990],
        [0.0653, 0.1039, 0.1027, 0.1146, 0.1015, 0.0726, 0.1246, 0.0995, 0.1050,
         0.1102]])
Sum:  1.0000001192092896


In [48]:
max_probs, preds=torch.max(probs,dim=1)
print(preds)
print(max_probs)

tensor([4, 6, 3, 6, 3, 9, 3, 3, 1, 3, 1, 3, 3, 1, 1, 3, 5, 3, 3, 3, 9, 7, 3, 9,
        6, 3, 3, 1, 1, 3, 4, 8, 3, 3, 1, 3, 1, 3, 4, 3, 7, 1, 9, 9, 1, 3, 3, 3,
        1, 9, 1, 7, 1, 1, 9, 3, 6, 3, 3, 8, 1, 3, 1, 3, 7, 8, 7, 1, 8, 1, 3, 1,
        8, 1, 1, 6, 4, 3, 3, 6, 3, 1, 3, 6, 4, 6, 6, 5, 9, 9, 1, 7, 6, 3, 1, 3,
        9, 1, 3, 3])
tensor([0.1254, 0.1246, 0.1212, 0.1228, 0.1318, 0.1318, 0.1473, 0.1416, 0.1222,
        0.1189, 0.1264, 0.1245, 0.1551, 0.1376, 0.1152, 0.1340, 0.1257, 0.1259,
        0.1296, 0.1219, 0.1297, 0.1245, 0.1315, 0.1250, 0.1283, 0.1560, 0.1498,
        0.1324, 0.1319, 0.1592, 0.1343, 0.1214, 0.1428, 0.1350, 0.1233, 0.1440,
        0.1259, 0.1441, 0.1253, 0.1296, 0.1314, 0.1325, 0.1313, 0.1303, 0.1241,
        0.1321, 0.1415, 0.1318, 0.1375, 0.1170, 0.1330, 0.1248, 0.1276, 0.1222,
        0.1289, 0.1417, 0.1120, 0.1212, 0.1320, 0.1287, 0.1359, 0.1293, 0.1576,
        0.1592, 0.1202, 0.1254, 0.1263, 0.1169, 0.1297, 0.1181, 0.1357, 0.1326,
        0.1165, 0.1

In [49]:
labels

tensor([5, 3, 5, 4, 9, 3, 8, 4, 9, 7, 5, 6, 7, 9, 1, 9, 0, 7, 4, 3, 1, 9, 5, 0,
        0, 7, 7, 4, 8, 9, 5, 1, 5, 6, 4, 2, 2, 5, 3, 6, 7, 5, 9, 3, 6, 4, 5, 8,
        6, 5, 2, 9, 5, 5, 3, 8, 9, 2, 8, 1, 3, 8, 8, 5, 9, 1, 2, 6, 4, 3, 7, 8,
        5, 8, 0, 2, 1, 7, 3, 5, 9, 4, 5, 2, 3, 8, 2, 4, 8, 9, 8, 7, 6, 7, 8, 6,
        9, 6, 2, 8])

In [50]:
labels==preds

tensor([False, False, False, False, False, False, False, False, False, False,
        False, False, False, False,  True, False, False, False, False,  True,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
         True, False,  True, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False,  True, False,
        False, False, False, False, False, False, False, False, False,  True,
        False,  True,  True, False, False, False,  True, False, False, False])

In [51]:
def accuracy(l1,l2):
    return torch.sum(l1==l2).item()/len(l1)

In [52]:
accuracy(preds,labels) 

0.09

In [53]:
loss_fn=F.cross_entropy

In [54]:
loss=loss_fn(outputs,labels)
print(loss)

tensor(2.3265, grad_fn=<NllLossBackward0>)


In [55]:
learning_rate=0.001
optimizer=torch.optim.SGD(model.parameters(),lr=learning_rate)

In [56]:
def loss_batch(model,loss_func,xb,yb,opt=None,metric=None):
    preds=model(xb)
    loss=loss_func(preds,yb)
    if opt is not None:
        loss.backward()
        opt.step()
        opt.zero_grad()

    metric_result=None
    if metric is not None:
        metric_result=metric(preds,yb)

    return loss.item(),len(xb), metric_result

In [57]:
def evaluate(model,loss_fn,valid_dl,metric=None):
    with torch.no_grad():
        results=[loss_batch(model,loss_fn,xb,yb,metric=metric)
        for xb,yb in valid_dl]
        losses,nums,metrics=zip(*results)
        total=np.sum(nums)
        avg_loss=np.sum(np.multiply(losses,nums))/total
        avg_metric=None
        if metric is not None:
            avg_metrics=np.sum(np.multiply(metrics,nums))/total
    return avg_loss,total,avg_metrics

In [58]:
def accuracy(outputs, labels):
    _,preds=torch.max(outputs,dim=1)
    return torch.sum(preds==labels).item()/len(preds)

In [59]:
val_loss,total,val_acc=evaluate(model,loss_fn,val_loader,metric=accuracy)
print('Loss: {:.4f}, Accuracy: {:.4f}'.format(val_loss,val_acc))

Loss: 2.3427, Accuracy: 0.0723


In [69]:
def fit(epochs,model,loss_fn,opt,train_dl,valid_dl,metric=None):
    for epoch in range(epochs):
        for xb,yb in train_dl:
            loss,_,_=loss_batch(model,loss_fn,xb,yb,opt)
            result=evaluate(model,loss_fn,valid_dl,metric)
            val_loss,total,val_metric=result
            if metric is None:
                print('Epoch[{}/{},Loss: {:.4f}]'.format(epoch+1,epochs,val_loss))
            else:
                print('Epoch[{}/{}, Loss: {:.4f}, {}: {:.4f}]'.format(epoch+1,epochs,val_loss,metric.__name__,val_metric))

In [61]:
model=MnistModel()
optimizer=torch.optim.SGD(model.parameters(),lr=learning_rate)

784


In [71]:
fit(1,model,F.cross_entropy,optimizer,train_loader,val_loader,accuracy)

Epoch[1/1, Loss: 2.0549, accuracy: 0.5090]
Epoch[1/1, Loss: 2.0540, accuracy: 0.5104]
Epoch[1/1, Loss: 2.0530, accuracy: 0.5112]
Epoch[1/1, Loss: 2.0521, accuracy: 0.5128]
Epoch[1/1, Loss: 2.0513, accuracy: 0.5133]
Epoch[1/1, Loss: 2.0504, accuracy: 0.5157]
Epoch[1/1, Loss: 2.0496, accuracy: 0.5166]
Epoch[1/1, Loss: 2.0488, accuracy: 0.5176]
Epoch[1/1, Loss: 2.0479, accuracy: 0.5188]
Epoch[1/1, Loss: 2.0470, accuracy: 0.5196]
Epoch[1/1, Loss: 2.0460, accuracy: 0.5222]
Epoch[1/1, Loss: 2.0451, accuracy: 0.5233]
Epoch[1/1, Loss: 2.0443, accuracy: 0.5236]
Epoch[1/1, Loss: 2.0434, accuracy: 0.5247]
Epoch[1/1, Loss: 2.0424, accuracy: 0.5256]
Epoch[1/1, Loss: 2.0415, accuracy: 0.5261]
Epoch[1/1, Loss: 2.0405, accuracy: 0.5271]
Epoch[1/1, Loss: 2.0395, accuracy: 0.5297]
Epoch[1/1, Loss: 2.0388, accuracy: 0.5310]
Epoch[1/1, Loss: 2.0379, accuracy: 0.5321]
Epoch[1/1, Loss: 2.0370, accuracy: 0.5335]
Epoch[1/1, Loss: 2.0362, accuracy: 0.5334]
Epoch[1/1, Loss: 2.0354, accuracy: 0.5344]
Epoch[1/1, 

In [72]:
test_dataset=MNIST(root='data/',train=False,transform=transforms.ToTensor())