In [1]:
import torch
import torchvision
from torchvision.datasets import MNIST
import numpy as np

D:\2_Miniconda\lib\site-packages\torchvision\io\image.py:11: UserWarning: Failed to load image Python extension: Could not find module 'D:\2_Miniconda\Lib\site-packages\torchvision\image.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
  warn(f"Failed to load image Python extension: {e}")


In [2]:
dataset=MNIST(root='data/',download=True)

In [3]:
len(dataset)

60000

In [4]:
test_dataset=MNIST(root='data/',train=False)
len(test_dataset)

10000

In [5]:
dataset[0]

(<PIL.Image.Image image mode=L size=28x28 at 0x1D36C4BDD90>, 5)

In [6]:
image,label=dataset[0]


In [7]:
import torchvision.transforms as transforms

In [8]:
dataset=MNIST(root='data/',train=True,transform=transforms.ToTensor())

In [9]:
img_tensor, label =dataset[0]
print(img_tensor.shape,label)

torch.Size([1, 28, 28]) 5


In [10]:
print(img_tensor[:,10:15,10:15])
print(torch.max(img_tensor),torch.min(img_tensor))

tensor([[[0.0039, 0.6039, 0.9922, 0.3529, 0.0000],
         [0.0000, 0.5451, 0.9922, 0.7451, 0.0078],
         [0.0000, 0.0431, 0.7451, 0.9922, 0.2745],
         [0.0000, 0.0000, 0.1373, 0.9451, 0.8824],
         [0.0000, 0.0000, 0.0000, 0.3176, 0.9412]]])
tensor(1.) tensor(0.)


In [11]:
n=6000
val_pct=0.2
n_val=int(val_pct*n)
idxs=np.random.permutation(n)
idxs


array([2992, 4888, 3878, ..., 2332, 5986,   64])

In [12]:


def split_indices(n, val_pct):
    n_val=int(val_pct*n)
    idxs=np.random.permutation(n)
    return idxs[n_val:], idxs[:n_val]

In [13]:
train_indices, val_indices=split_indices(len(dataset),val_pct=0.2)

In [14]:
print(len(train_indices),len(val_indices))
print('Sample val indices: ',val_indices[:20])

48000 12000
Sample val indices:  [30185 59361 13822   675 51819 12097 43860 45099 58392  1917 26937 28733
 38702 18043 57054 16683 52246 26035 44044 25087]


In [15]:
from torch.utils.data.sampler import SubsetRandomSampler
from torch.utils.data.dataloader import DataLoader

In [16]:
batch_size=100

train_sampler=SubsetRandomSampler(train_indices)
train_loader=DataLoader(dataset,batch_size,sampler=train_sampler)

val_sampler=SubsetRandomSampler(val_indices)
val_loader=DataLoader(dataset,batch_size,sampler=val_sampler)

In [17]:
import torch.nn as nn
input_size=28*28
num_classes=10

model=nn.Linear(input_size,num_classes)

In [18]:
print(model.weight.shape)
model.weight

torch.Size([10, 784])


Parameter containing:
tensor([[-2.4675e-02, -9.5151e-05,  3.0872e-02,  ..., -1.0981e-02,
         -1.5725e-02, -3.2452e-02],
        [-2.6830e-02, -1.4289e-02,  3.1132e-02,  ..., -6.3351e-03,
          3.2745e-02, -4.2256e-04],
        [ 8.8047e-03, -1.7969e-02,  1.6760e-02,  ..., -6.2440e-03,
         -9.6600e-03,  1.5863e-02],
        ...,
        [-3.2186e-02, -1.0005e-02,  1.6838e-02,  ...,  1.0492e-02,
         -2.2759e-02,  3.5356e-02],
        [-8.9106e-03,  7.9032e-03,  2.9516e-02,  ..., -8.7289e-03,
          2.0084e-02, -2.7358e-02],
        [-2.2860e-02,  3.0383e-02,  5.4909e-03,  ..., -1.2551e-03,
         -3.0755e-02, -3.0208e-02]], requires_grad=True)

In [19]:
print(model.bias.shape)
model.bias

torch.Size([10])


Parameter containing:
tensor([-0.0031, -0.0137,  0.0226, -0.0265, -0.0328, -0.0228, -0.0087, -0.0094,
         0.0293,  0.0308], requires_grad=True)

In [20]:
for images, labels in train_loader:
    print(labels)
    print(images.shape)
    outputs=model(images)
    break

tensor([9, 0, 6, 3, 4, 5, 7, 9, 9, 3, 1, 2, 7, 8, 1, 2, 1, 2, 8, 5, 5, 4, 0, 6,
        8, 9, 1, 1, 0, 6, 0, 4, 9, 4, 8, 8, 9, 7, 9, 1, 7, 8, 6, 2, 8, 5, 9, 4,
        6, 7, 2, 9, 9, 5, 4, 2, 0, 3, 1, 6, 7, 1, 7, 1, 5, 9, 1, 4, 4, 6, 9, 6,
        8, 6, 8, 9, 5, 6, 2, 2, 0, 9, 5, 0, 3, 7, 9, 6, 0, 6, 1, 3, 4, 9, 7, 6,
        6, 2, 9, 7])
torch.Size([100, 1, 28, 28])


RuntimeError: mat1 and mat2 shapes cannot be multiplied (2800x28 and 784x10)

In [ ]:
class MnistModel(nn.Module):

    def __init__(self):
        print(input_size)
        super().__init__()
        self.linear=nn.Linear(input_size,num_classes)

    def forward(self,xb):
        
        xb=xb.reshape(-1,784)
        out=self.linear(xb)
        return out
    
model=MnistModel()

784


In [ ]:
print(model.linear.weight.shape, model.linear.bias.shape)
list(model.parameters())

torch.Size([10, 784]) torch.Size([10])


[Parameter containing:
 tensor([[ 0.0291, -0.0249, -0.0031,  ..., -0.0263, -0.0212,  0.0032],
         [ 0.0094,  0.0140,  0.0275,  ...,  0.0028,  0.0329, -0.0304],
         [-0.0116,  0.0164,  0.0068,  ...,  0.0028,  0.0225,  0.0003],
         ...,
         [ 0.0134, -0.0278,  0.0137,  ..., -0.0234, -0.0345, -0.0018],
         [-0.0087, -0.0265,  0.0212,  ...,  0.0019,  0.0249,  0.0069],
         [ 0.0072,  0.0225, -0.0097,  ...,  0.0101, -0.0196, -0.0168]],
        requires_grad=True),
 Parameter containing:
 tensor([-0.0290,  0.0051,  0.0105, -0.0087,  0.0079,  0.0239, -0.0284,  0.0003,
         -0.0034, -0.0133], requires_grad=True)]

In [ ]:
for images, labels in train_loader:
    outputs=model(images)
    
    break
print('outputs.shape: ',outputs.shape)
print("Sample outputs:\n",outputs[:2].data)


outputs.shape:  torch.Size([100, 10])
Sample outputs:
 tensor([[ 0.1212,  0.0575, -0.0891, -0.1491, -0.1927,  0.0548,  0.0751, -0.0460,
         -0.0754, -0.1047],
        [ 0.2315, -0.2315, -0.0373, -0.3314,  0.0703, -0.1276, -0.0037,  0.0239,
          0.0107,  0.1095]])


ModuleNotFoundError: No module named 'matplotlib'