In [1]:
import torch
import torchvision
from torchvision.datasets import MNIST

D:\2_Miniconda\lib\site-packages\torchvision\io\image.py:11: UserWarning: Failed to load image Python extension: Could not find module 'D:\2_Miniconda\Lib\site-packages\torchvision\image.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
  warn(f"Failed to load image Python extension: {e}")


In [2]:
dataset=MNIST(root='data/',download=True)

In [3]:
len(dataset)

60000

In [4]:
test_dataset=MNIST(root='data/',train=False)
len(test_dataset)

10000

In [5]:
dataset[0]

(<PIL.Image.Image image mode=L size=28x28 at 0x16AA2567EB0>, 5)

In [22]:
import matplotlib.pyplot as plt


In [7]:
image,label=dataset[0]


In [8]:
import torchvision.transforms as transforms

In [9]:
dataset=MNIST(root='data/',train=True,transform=transforms.ToTensor())

In [10]:
img_tensor, label =dataset[0]
print(img_tensor.shape,label)

torch.Size([1, 28, 28]) 5


In [11]:
print(img_tensor[:,10:15,10:15])
print(torch.max(img_tensor),torch.min(img_tensor))

tensor([[[0.0039, 0.6039, 0.9922, 0.3529, 0.0000],
         [0.0000, 0.5451, 0.9922, 0.7451, 0.0078],
         [0.0000, 0.0431, 0.7451, 0.9922, 0.2745],
         [0.0000, 0.0000, 0.1373, 0.9451, 0.8824],
         [0.0000, 0.0000, 0.0000, 0.3176, 0.9412]]])
tensor(1.) tensor(0.)


In [16]:
n=6000
val_pct=0.2
n_val=int(val_pct*n)
idxs=np.random.permutation(n)
idxs


array([4479, 5001, 4390, ..., 4339, 4618, 3834])

In [14]:
import numpy as np

def split_indices(n, val_pct):
    n_val=int(val_pct*n)
    idxs=np.random.permutation(n)
    return idxs[n_val:], idxs[:n_val]

In [17]:
train_indices, val_indices=split_indices(len(dataset),val_pct=0.2)

In [19]:
print(len(train_indices),len(val_indices))
print('Sample val indices: ',val_indices[:20])

48000 12000
Sample val indices:  [38518  7736 43555 53520 32977 27172 24140 28788 17006 46952  5486 50224
 18780 29808 22067 28062 33291 38191 25505 55015]


In [20]:
from torch.utils.data.sampler import SubsetRandomSampler
from torch.utils.data.dataloader import DataLoader

In [21]:
batch_size=100

train_sampler=SubsetRandomSampler(train_indices)
train_loader=DataLoader(dataset,batch_size,sampler=train_sampler)

val_sampler=SubsetRandomSampler(val_indices)
val_loader=DataLoader(dataset,batch_size,sampler=val_sampler)

In [23]:
import torch.nn as nn
input_size=28*28
num_classes=10

model=nn.Linear(input_size,num_classes)

In [24]:
print(model.weight.shape)
model.weight

torch.Size([10, 784])


Parameter containing:
tensor([[-0.0023,  0.0161,  0.0280,  ..., -0.0215, -0.0197, -0.0341],
        [-0.0064, -0.0223,  0.0004,  ...,  0.0228,  0.0319, -0.0046],
        [-0.0161, -0.0093,  0.0055,  ..., -0.0257, -0.0082,  0.0336],
        ...,
        [-0.0023, -0.0131,  0.0093,  ...,  0.0002,  0.0243,  0.0062],
        [ 0.0103,  0.0127, -0.0254,  ...,  0.0078,  0.0028,  0.0172],
        [ 0.0350, -0.0059, -0.0122,  ...,  0.0182,  0.0217, -0.0042]],
       requires_grad=True)

In [25]:

%matplotlib inline

In [26]:
print(model.bias.shape)
model.bias

torch.Size([10])


Parameter containing:
tensor([ 0.0009,  0.0214,  0.0254, -0.0206, -0.0316,  0.0295, -0.0142,  0.0129,
         0.0301,  0.0323], requires_grad=True)

In [27]:
for images, labels in train_loader:
    print(labels)
    print(images.shape)
    outputs=model(images)
    break

tensor([0, 8, 9, 5, 1, 8, 2, 8, 8, 1, 3, 5, 1, 4, 4, 6, 7, 6, 4, 2, 9, 9, 6, 2,
        3, 0, 1, 8, 8, 9, 3, 3, 3, 4, 2, 6, 4, 4, 9, 6, 0, 0, 1, 2, 7, 9, 6, 7,
        8, 9, 2, 9, 0, 6, 7, 6, 1, 5, 7, 8, 2, 8, 5, 2, 3, 1, 0, 8, 1, 4, 8, 4,
        5, 4, 1, 0, 1, 0, 0, 3, 0, 8, 9, 3, 1, 8, 4, 9, 2, 8, 0, 1, 3, 2, 6, 3,
        5, 2, 5, 7])
torch.Size([100, 1, 28, 28])


RuntimeError: mat1 and mat2 shapes cannot be multiplied (2800x28 and 784x10)