In [48]:
import torch
import torchvision
from torchvision.datasets import MNIST
import numpy as np

In [49]:
dataset=MNIST(root='data/',download=True)

In [50]:
len(dataset)

60000

In [51]:
test_dataset=MNIST(root='data/',train=False)
len(test_dataset)

10000

In [52]:
dataset[0]

(<PIL.Image.Image image mode=L size=28x28 at 0x1A200018088>, 5)

In [53]:
image,label=dataset[0]


In [54]:
import torchvision.transforms as transforms

In [55]:
dataset=MNIST(root='data/',train=True,transform=transforms.ToTensor())

In [56]:
img_tensor, label =dataset[0]
print(img_tensor.shape,label)

torch.Size([1, 28, 28]) 5


In [57]:
print(img_tensor[:,10:15,10:15])
print(torch.max(img_tensor),torch.min(img_tensor))

tensor([[[0.0039, 0.6039, 0.9922, 0.3529, 0.0000],
         [0.0000, 0.5451, 0.9922, 0.7451, 0.0078],
         [0.0000, 0.0431, 0.7451, 0.9922, 0.2745],
         [0.0000, 0.0000, 0.1373, 0.9451, 0.8824],
         [0.0000, 0.0000, 0.0000, 0.3176, 0.9412]]])
tensor(1.) tensor(0.)


In [58]:
n=6000
val_pct=0.2
n_val=int(val_pct*n)
idxs=np.random.permutation(n)
idxs


array([4983, 1607, 3700, ..., 1803, 1130, 1687])

In [59]:


def split_indices(n, val_pct):
    n_val=int(val_pct*n)
    idxs=np.random.permutation(n)
    return idxs[n_val:], idxs[:n_val]

In [60]:
train_indices, val_indices=split_indices(len(dataset),val_pct=0.2)

In [61]:
print(len(train_indices),len(val_indices))
print('Sample val indices: ',val_indices[:20])

48000 12000
Sample val indices:  [15763 27511 10359 42175 44677 38804 57357 34474   710 11699 34142 15481
 10559 53772 22739  8374  9897 15906 36776 33395]


In [62]:
from torch.utils.data.sampler import SubsetRandomSampler
from torch.utils.data.dataloader import DataLoader

In [63]:
batch_size=100

train_sampler=SubsetRandomSampler(train_indices)
train_loader=DataLoader(dataset,batch_size,sampler=train_sampler)

val_sampler=SubsetRandomSampler(val_indices)
val_loader=DataLoader(dataset,batch_size,sampler=val_sampler)

In [64]:
import torch.nn as nn
input_size=28*28
num_classes=10

model=nn.Linear(input_size,num_classes)

In [65]:
print(model.weight.shape)
model.weight

torch.Size([10, 784])


Parameter containing:
tensor([[ 0.0194,  0.0290,  0.0237,  ...,  0.0102,  0.0063,  0.0096],
        [ 0.0211,  0.0056, -0.0258,  ..., -0.0057, -0.0213,  0.0015],
        [ 0.0219, -0.0103,  0.0222,  ..., -0.0188, -0.0120, -0.0020],
        ...,
        [ 0.0239, -0.0146, -0.0347,  ...,  0.0089,  0.0023, -0.0111],
        [-0.0159,  0.0181, -0.0289,  ...,  0.0068,  0.0223, -0.0179],
        [-0.0208,  0.0355, -0.0119,  ..., -0.0342, -0.0326, -0.0051]],
       requires_grad=True)

In [66]:
print(model.bias.shape)
model.bias

torch.Size([10])


Parameter containing:
tensor([ 0.0090,  0.0284,  0.0031,  0.0194,  0.0162, -0.0270, -0.0016, -0.0328,
         0.0192,  0.0020], requires_grad=True)

In [67]:
for images, labels in train_loader:
    print(labels)
    print(images.shape)
    outputs=model(images)
    break

tensor([6, 3, 1, 5, 6, 7, 1, 9, 1, 0, 9, 7, 7, 0, 8, 6, 5, 8, 2, 7, 3, 2, 8, 7,
        9, 6, 4, 2, 1, 8, 7, 9, 1, 2, 6, 6, 9, 8, 0, 3, 6, 6, 7, 6, 0, 2, 6, 3,
        2, 3, 2, 0, 0, 6, 2, 2, 1, 2, 7, 3, 9, 0, 9, 1, 9, 2, 9, 6, 4, 8, 6, 7,
        0, 2, 2, 1, 7, 8, 1, 0, 0, 1, 1, 9, 2, 5, 3, 5, 5, 3, 4, 7, 4, 5, 1, 8,
        2, 4, 3, 2])
torch.Size([100, 1, 28, 28])


RuntimeError: mat1 and mat2 shapes cannot be multiplied (2800x28 and 784x10)

In [ ]:
class MnistModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear=nn.Linear(input_size,num_classes)

    def forward(self,xb):
        xb=xb.reshape(-1,784)
        out=self.linear(xb)
    
model=MnistModel()