In [1]:
import torch
import numpy as np

In [11]:
inputs=np.array([[73,67,43],
[91,88,64],
[87,134,58],
[102,43,37],
[69,96,70]],dtype='float32')

In [12]:
targets=np.array([[56,70],
[81,101],
[119,133],
[22,37],
[103,119]],dtype='float32')

In [13]:
inputs=torch.from_numpy(inputs)
targets=torch.from_numpy(targets)
print(inputs)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])


In [14]:
w=torch.randn(2,3,requires_grad=True)
b=torch.randn(2,requires_grad=True)
print(w)
print(b)

tensor([[-0.2880, -1.7213, -1.3588],
        [ 0.5298,  1.3681,  0.6497]], requires_grad=True)
tensor([ 1.4697, -0.0780], requires_grad=True)


In [15]:
def model(x):
    return x @ w.t()+b