In [1]:
import torch
import numpy as np

In [11]:
inputs=np.array([[73,67,43],
[91,88,64],
[87,134,58],
[102,43,37],
[69,96,70]],dtype='float32')

In [12]:
targets=np.array([[56,70],
[81,101],
[119,133],
[22,37],
[103,119]],dtype='float32')

In [13]:
inputs=torch.from_numpy(inputs)
targets=torch.from_numpy(targets)
print(inputs)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])


In [17]:
w=torch.randn(2,3,requires_grad=True)
b=torch.randn(2,requires_grad=True)
print(w)
print(b)

tensor([[-0.8433, -1.0182, -1.0400],
        [ 0.1418, -0.0664, -1.1317]], requires_grad=True)
tensor([1.5669, 0.2428], requires_grad=True)


In [15]:
def model(x):
    return x @ w.t()+b

In [18]:
preds=model(inputs)
print(preds)

tensor([[-172.9344,  -42.5152],
        [-231.3361,  -65.1223],
        [-268.5614,  -61.9535],
        [-166.7130,  -30.0184],
        [-227.1691,  -75.5639]], grad_fn=<AddBackward0>)


In [19]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [20]:
diff=preds-targets
diff_sq=diff*diff
torch.sum(diff_sq)/diff.numel()

tensor(56540.2617, grad_fn=<DivBackward0>)

In [21]:
def mse(t1,t2):
    diff=t1-t2
    return torch.sum(diff*diff/diff.numel())

In [22]:
loss=mse(preds,targets)
print(loss)

tensor(56540.2578, grad_fn=<SumBackward0>)
