In [10]:
import torch.nn as nn
import numpy as np
import torch

In [4]:
inputs=np.array([[73,67,43],
[91,88,64],
[87,134,58],
[102,43,37],
[69,96,70]],dtype='float32')

In [7]:
targets=np.array([[56,70],
[81,101],
[119,133],
[22,37],
[103,119]],dtype='float32')

In [11]:
inputs=torch.from_numpy(inputs)
targets=torch.from_numpy(targets)

In [12]:
from torch.utils.data import TensorDataset

In [13]:
train_ds=TensorDataset(inputs,targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [18]:
from torch.utils.data import DataLoader

In [19]:
batch_size=5
train_dl=DataLoader(train_ds,batch_size,shuffle=True)

In [20]:
for xb, yb in train_dl:
    print(xb)
    print(yb)

tensor([[ 91.,  88.,  64.],
        [ 69.,  96.,  70.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 73.,  67.,  43.]])
tensor([[ 81., 101.],
        [103., 119.],
        [119., 133.],
        [ 22.,  37.],
        [ 56.,  70.]])


In [21]:
model=nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.4403,  0.4471,  0.1624],
        [-0.4983, -0.4033, -0.1553]], requires_grad=True)
Parameter containing:
tensor([-0.2742,  0.0544], requires_grad=True)


In [22]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.4403,  0.4471,  0.1624],
         [-0.4983, -0.4033, -0.1553]], requires_grad=True),
 Parameter containing:
 tensor([-0.2742,  0.0544], requires_grad=True)]

In [23]:
preds=model(inputs)
preds

tensor([[  68.8062,  -70.0204],
        [  89.5307,  -90.7199],
        [ 107.3635, -106.3462],
        [  69.8693,  -73.8618],
        [  84.3955,  -83.9143]], grad_fn=<AddmmBackward0>)

In [24]:
import torch.nn.functional as F

In [25]:
loss_fn=F.mse_loss

In [26]:
loss=loss_fn(model(inputs),targets)
print(loss)

tensor(17012.3203, grad_fn=<MseLossBackward0>)


In [27]:
opt=torch.optim.SGD(model.parameters(),lr=1e-5)

In [30]:
def fit(num_epochs,model, loss_fn,opt):
    for epoch in range(num_epochs):
        for xb,yb in train_dl:
            pred=model(xb)
            loss=loss_fn(pred,yb)
            loss.backward()
            opt.step()
            opt.zero_grad()

        if(epoch+1)%10==0:
            print('Epoch [{}/{}, Loss: {:.4f}'.format(epoch+1,num_epochs,loss.item()))

In [38]:
fit(500,model,loss_fn,opt)

Epoch [10/500, Loss: 0.5455
Epoch [20/500, Loss: 0.5449
Epoch [30/500, Loss: 0.5443
Epoch [40/500, Loss: 0.5437
Epoch [50/500, Loss: 0.5431
Epoch [60/500, Loss: 0.5425
Epoch [70/500, Loss: 0.5420
Epoch [80/500, Loss: 0.5414
Epoch [90/500, Loss: 0.5409
Epoch [100/500, Loss: 0.5403
Epoch [110/500, Loss: 0.5398
Epoch [120/500, Loss: 0.5393
Epoch [130/500, Loss: 0.5388
Epoch [140/500, Loss: 0.5383
Epoch [150/500, Loss: 0.5378
Epoch [160/500, Loss: 0.5373
Epoch [170/500, Loss: 0.5369
Epoch [180/500, Loss: 0.5364
Epoch [190/500, Loss: 0.5360
Epoch [200/500, Loss: 0.5355
Epoch [210/500, Loss: 0.5351
Epoch [220/500, Loss: 0.5347
Epoch [230/500, Loss: 0.5342
Epoch [240/500, Loss: 0.5338
Epoch [250/500, Loss: 0.5334
Epoch [260/500, Loss: 0.5330
Epoch [270/500, Loss: 0.5326
Epoch [280/500, Loss: 0.5323
Epoch [290/500, Loss: 0.5319
Epoch [300/500, Loss: 0.5315
Epoch [310/500, Loss: 0.5311
Epoch [320/500, Loss: 0.5308
Epoch [330/500, Loss: 0.5304
Epoch [340/500, Loss: 0.5301
Epoch [350/500, Loss: 0

In [39]:
preds=model(inputs)
preds

tensor([[ 57.1285,  70.3289],
        [ 82.1529, 100.5839],
        [118.8740, 133.1231],
        [ 21.1359,  37.0605],
        [101.7398, 118.9734]], grad_fn=<AddmmBackward0>)

In [40]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])