In [10]:
import torch.nn as nn
import numpy as np
import torch

In [4]:
inputs=np.array([[73,67,43],
[91,88,64],
[87,134,58],
[102,43,37],
[69,96,70]],dtype='float32')

In [7]:
targets=np.array([[56,70],
[81,101],
[119,133],
[22,37],
[103,119]],dtype='float32')

In [11]:
inputs=torch.from_numpy(inputs)
targets=torch.from_numpy(targets)

In [12]:
from torch.utils.data import TensorDataset

In [13]:
train_ds=TensorDataset(inputs,targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [18]:
from torch.utils.data import DataLoader

In [19]:
batch_size=5
train_dl=DataLoader(train_ds,batch_size,shuffle=True)

In [20]:
for xb, yb in train_dl:
    print(xb)
    print(yb)

tensor([[ 91.,  88.,  64.],
        [ 69.,  96.,  70.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 73.,  67.,  43.]])
tensor([[ 81., 101.],
        [103., 119.],
        [119., 133.],
        [ 22.,  37.],
        [ 56.,  70.]])


In [21]:
model=nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.4403,  0.4471,  0.1624],
        [-0.4983, -0.4033, -0.1553]], requires_grad=True)
Parameter containing:
tensor([-0.2742,  0.0544], requires_grad=True)


In [22]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.4403,  0.4471,  0.1624],
         [-0.4983, -0.4033, -0.1553]], requires_grad=True),
 Parameter containing:
 tensor([-0.2742,  0.0544], requires_grad=True)]

In [23]:
preds=model(inputs)
preds

tensor([[  68.8062,  -70.0204],
        [  89.5307,  -90.7199],
        [ 107.3635, -106.3462],
        [  69.8693,  -73.8618],
        [  84.3955,  -83.9143]], grad_fn=<AddmmBackward0>)

In [24]:
import torch.nn.functional as F

In [25]:
loss_fn=F.mse_loss

In [26]:
loss=loss_fn(model(inputs),targets)
print(loss)

tensor(17012.3203, grad_fn=<MseLossBackward0>)


In [27]:
opt=torch.optim.SGD(model.parameters(),lr=1e-5)